#!/usr/bin/env bash

# Color files
RFILE="$HOME/scripts/rofi/i3-notifier-colors.rasi"

# Change colors
change_color() {
	# rofi
	cat > $RFILE <<- EOF
	/* colors */

	* {
	  al:    ${SH8}FF;
	  bg:    ${BG}FF;
	  bg1:   ${SH1}FF;
	  bg2:   ${SH2}FF;
	  bg3:   ${SH3}FF;
	  fg:    ${FG}FF;
	}
	EOF
	
	polybar-msg cmd restart
}

# Main
if [[ -f "/usr/bin/wal" ]]; then
    # Source the pywal color file
    . "$HOME/.cache/wal/colors.sh"

    BG=`printf "%s\n" "$background"`
    FG=`printf "%s\n" "$foreground"`
    FGA=`printf "%s\n" "$foreground"`
    SH1=`printf "%s\n" "$color1"`
    SH2=`printf "%s\n" "$color2"`
    SH3=`printf "%s\n" "$color3"`
    SH4=`printf "%s\n" "$color4"`
    SH5=`printf "%s\n" "$color5"`
    SH6=`printf "%s\n" "$color6"`
    SH7=`printf "%s\n" "$color7"`
    SH8=`printf "%s\n" "$color8"`
        
    change_color
else
	echo "[!] 'pywal' is not installed."
fi
