FZF_HEIGHT="100%"
export FZF_DEFAULT_OPTS="
	--color fg:7:dim,bg:0,hl:15:bold:underline,fg+:7:regular,bg+:8,hl+:15:bold:underline
	--color gutter:1:bold,scrollbar:15:dim,label:7:bold
	--color border:8,info:7:dim,prompt:1:bold,spinner:15:dim
	--color pointer:1,marker:15:dim,separator:8,header:7
	--color preview-bg:0,preview-border:8
	--color preview-scrollbar:15:dim,preview-label:7:bold
	--height=~$FZF_HEIGHT
	--gutter=' '
	--style=minimal
	--scrollbar='┃'
	--cycle
	--info=default
	--preview-window 70%:hidden:border-rounded
	--preview 'lesspipe.sh {}'
	--preview-label=' Preview '
	--pointer=' '
	--marker='┃'
	--prompt=' '
	--highlight-line
	--tabstop=4
	--layout=reverse
	--margin=0,0
	--padding=0,0
	--multi
	--bind '?:toggle-preview'
	--bind 'enter:accept'
	--bind 'ctrl-b:backward-word'
	--bind 'ctrl-f:forward-word'
	--bind 'alt-b:backward-char'
	--bind 'alt-f:forward-char'
	--bind 'ctrl-q:toggle'
	--bind 'alt-q:toggle-all'
	--bind 'ctrl-z:jump'
	--bind 'ctrl-j:down'
	--bind 'ctrl-k:up'
	--bind 'alt-j:half-page-down'
	--bind 'alt-k:half-page-up'
	--bind 'ctrl-n:preview-down'
	--bind 'ctrl-p:preview-up'
	--bind 'alt-p:preview-half-page-up'
	--bind 'alt-n:preview-half-page-down'
	--bind 'tab:down'
	--bind 'shift-tab:up'"
