foreground   #c1c1c1
background   #222222
cursor       #dfdfdf

color0       #222222
color8       #da6a64
color1       #974b46
color9       #da6a64
color2       #619292
color10      #76b2b2
color3       #7a8985
color11      #aac0ba
color4       #999999
color12      #bababa
color5       #aaaaaa
color13      #c3c3c3
color6       #888888
color14      #a2a2a2
color7       #c1c1c1
color15      #dfdfdf
