# :.config/kitty/kitty-theme.conf

foreground   #f6f6f6
background   #101010
cursor       #e3e3e3

color0       #101010
color8       #353535
color1       #b67262
color9       #bc8778
color2       #8a9273
color10      #a0ac82
color3       #c0a474
color11      #c3ae8b
color4       #78859e
color12      #8f9cae
color5       #9b859d
color13      #a392a5
color6       #a8d2db
color14      #b9d8df
color7       #f6f6f6
color15      #e3e3e3
