# :.config/aria2/aria2.conf
continue
daemon=true
dir=/home/lckdscl/downloads
log=/home/lckdscl/.cache/aria2/log
log-level=warn
max-connection-per-server=4
max-concurrent-downloads=3
max-overall-download-limit=0
min-split-size=5M
enable-http-pipelining=true

enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-secret=lckdscl-void
