# :.config/bat/config
--theme="wal"
--italic-text=always
--paging=auto
--pager="less --RAW-CONTROL-CHARS --quit-if-one-screen --mouse"
--map-syntax "*.ino:C++"
--map-syntax ".ignore:Git Ignore"
--map-syntax "*rc:INI"
--map-syntax "*.conf:INI"
--color=auto
--style=numbers
