# :.config/bpytop/bpytop.conf
color_theme="+bpytop"
theme_background=False
truecolor=True
shown_boxes="cpu mem net proc"
update_ms=2000
proc_update_mult=2
proc_sorting="cpu lazy"
proc_reversed=False
proc_tree=False
tree_depth=3
proc_colors=True
proc_gradient=False
proc_per_core=True
proc_mem_bytes=True
cpu_graph_upper="total"
cpu_graph_lower="total"
cpu_invert_lower=True
cpu_single_graph=False
show_uptime=True
check_temp=True
cpu_sensor=Auto
show_coretemp=True
temp_scale="celsius"
show_cpu_freq=True
draw_clock=""
background_update=True
custom_cpu_name=""
disks_filter="exclude=/boot, /dev/mapper/swap"
mem_graphs=True
show_swap=True
swap_disk=True
show_disks=True
only_physical=True
use_fstab=False
show_io_stat=True
io_mode=False
io_graph_combined=False
io_graph_speeds=""
net_download="10M"
net_upload="10M"
net_auto=True
net_sync=False
net_color_fixed=False
net_iface=""
show_battery=False
show_init=False
update_check=True
log_level=WARNING
