# :.config/cava/config

[general]
framerate = 144
autosens = 1
overshoot = 20
sensitivity = 50
bars = 0
bar_width = 1
bar_spacing = 1
lower_cutoff_freq = 50
higher_cutoff_freq = 10000
sleep_timer = 20


[input]
method = pulse
source = auto


[output]
method = ncurses
channels = stereo
mono_option = average

[color]
background = default
foreground = '#CC523B'

[smoothing]
integral = 77
monstercat = 1
waves = 1
gravity = 150
# ignore = 0


[eq]
1=2
2=2
3=1
4=1
5=0.5
