# :.config/kitty/kitty-theme.conf

foreground   #c7ccd1
background   #222222
cursor       #f8f9fa

color0       #222222
color8       #272727
color1       #c7ae95
color9       #d9bea2
color2       #94c5ad
color10      #a2d9bf
color3       #aec795
color11      #c3dea7
color4       #ae95c7
color12      #c5a9e0
color5       #c795ae
color13      #dba4c1
color6       #95aec7
color14      #a8c6e2
color7       #c7ccd1
color15      #f8f9fa
