# :.config/newsboat/config
auto-reload yes
reload-time 45
reload-threads 100
download-full-page yes
display-article-progress yes
confirm-mark-all-feeds-read yes
confirm-delete-all-articles yes
cleanup-on-quit yes
color background          white   black
color listnormal          color8  black
color listfocus           yellow  color8 bold
color listnormal_unread   white   black
color listfocus_unread    yellow  color8 bold
color info                red     black  bold
color article             white   black
