# :.config/newsboat/urls
https://xkcd.com/atom.xml comic "~xkcd"
http://feeds.feedburner.com/InformationIsBeautiful curated "~Information Is Beautiful"
https://www.eff.org/rss/updates.xml curated "~Electronic Frontier Foundation"
http://feeds.feedburner.com/itsfoss curated "~It's FOSS"
https://www.lesswrong.com/feed.xml?view=frontpage-rss&amp;amp;karmaThreshold=2 curated "~LessWrong"
https://feeds.feedburner.com/MappingIgnorance curated "~Mapping Ignorance"
http://feeds.feedburner.com/MeltingAsphalt curated "~Melting Asphalt"
https://nesslabs.com/feed curated "~NessLabs"
https://www.phoronix.com/rss.php curated "~Phoronix"
https://levels.io/rss/ curated "~Pieter Levels"
https://api.quantamagazine.org/feed/ curated "~Quanta Magazine"
https://feeds.npr.org/1007/rss.xml curated "~NPR Science"
https://flowingdata.com/feed curated "~Flowing Data"
https://newsletter.decisionschool.org/feed curated "~Decision School"
https://www.preposterousuniverse.com/blog/feed/ curated "~Sean Carroll"
https://waitbutwhy.com/feed curated "~Wait But Why"
https://wellnesswisdom.substack.com/feed curated "~Wellness Wisdom"
https://www.ghacks.net/feed/ curated "~Ghacks"
https://www.symmetrymagazine.org/feed curated "~Symmetry Magazine"
https://feeds.bbci.co.uk/news/world/rss.xml headlines "~BBC World News"
https://www.theguardian.com/international/rss headlines "~The Guardian"
http://www.independent.co.uk/rss headlines "~The Independent"
https://www.kernel.org/feeds/kdist.xml linux "~Linux Kernel"
