[settings]
set_wallpaper = true
gtk = true
active = 1
light_theme = false
editor = kitty -e nvim
execute_cmd = true
command = pywal-discord && spicetify update && xsettingsd -c "$XDG_CONFIG_HOME"/xsettingsd/xsettingsd.conf &
backend = wal
alpha = 100
smart_sort = true
auto_adjust = false
reload = true
vte = true

[keywords]
border-radius = 2
icons = Fluent-dark
font0 = JetBrainsMono Nerd Font Mono
font-size = 10
font-size-icon = 14
cursor = Bibata-Modern-Classic
show-icons = true

