# :.zshenv
# ENVIRONMENTAL VARIABLES
export LANG=en_GB.UTF-8
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
# ------------------------------------
export VIT_DIR="$XDG_CONFIG_HOME"/vit
export TASKRC="$XDG_CONFIG_HOME"/task/taskrc
export TASKDATA="$HOME"/task
export DIFFPROG=nvim
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export ENABLE_VKBASALT=0
export MANGOHUD=0
export IPFS_PATH="$XDG_DATA_HOME"/ipfs
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export STACK_ROOT="$XDG_DATA_HOME"/stack
export IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export EDITOR=/usr/bin/nvim
export XCURSOR_THEME=Bibata-Modern-Classic
export TERMINAL="/usr/bin/kitty"
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default
export ADOTDIR="$XDG_DATA_HOME"/antigen
export BROWSER="/usr/bin/brave"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export WEECHAT_HOME="$XDG_CONFIG_HOME"/weechat
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT4_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus
export BAT_CONFIG_PATH="$XDG_CONFIG_HOME"/bat/config
