# :.config/colorls/dark_colors.yaml
# Main Colors
unrecognized_file: magenta
recognized_file:   yellow
executable_file:   green
dir:               blue

# Link
dead_link: red
link:      cyan

# special files
socket:    green
blockdev:  green
chardev:   green

# Access Modes
write:     green
read:      blue
exec:      red
no_access: gray

# Age
day_old:     lightgreen
hour_old:    green
no_modifier: seagreen

# File Size
file_large:  orange
file_medium: gold
file_small:  peachpuff

# Random
report: white
user:   cyan
tree:   dimgray
empty:  yellow
error:  red
normal: darkkhaki

# Git
addition:     magenta
modification: yellow
deletion:     red
untracked:    cyan
unchanged:    green
