; :.config/spicetify/config-xpui.ini

[Setting]
spotify_path            = /opt/spotify
color_scheme            = pywal
spotify_launch_flags    = 
prefs_path              = /home/lckdscl/.config/spotify/prefs
current_theme           = SpicetifyDefault
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 0
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions     = hidePodcasts.js|fullAppDisplay.js|shuffle+.js|trashbin.js|keyboardShortcut.js|popupLyrics.js|bookmark.js 
custom_apps    = reddit|new-releases
sidebar_config = 1
home_config    = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.1.56.595.g2d2da0de
with    = 
