# :.config/mpv/mpv.conf
[1080p]
ytdl-format=bestvideo[height<=?1080]+bestaudio/best

sub-auto=fuzzy
sub-bold=yes
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
slang=en
hwdec=auto-safe
window-scale=0.7
ontop=yes
border=no
vo=gpu
osc=no
