#!/usr/bin/env bash

ACTIONS=("restore" "save" "delete")
TARGETS=("both" "programs" "layout")
DMENU="dmenu -i"

prompt="i3-resurrect"
action=$(printf "%s\n" ${ACTIONS[@]} | $DMENU -p $prompt)

case $action in
  save)
    command="i3-resurrect save --swallow=class,title -p"
    ;;
  restore)
    command="i3-resurrect restore -p"
    ;;
  delete)
    command="i3-resurrect rm -p"
    ;;
  *)
    echo "invalid action"
    exit 1
    ;;
esac

prompt="profile"
profile=$(i3-resurrect ls profiles | awk '{$NF=""; $1=""; print $0}' | uniq | $DMENU -p "$prompt" | xargs)

if [[ "$profile" == "" ]]; then
  echo "invalid profile"
  exit 1
fi

prompt="target"
target=$(printf "%s\n" ${TARGETS[@]} | $DMENU -p $prompt)

case $target in
  programs)
    target_option="--programs-only"
    ;;
  layout)
    target_option="--layout-only"
    ;;
  both)
    target_option=""
    ;;
  *)
    echo "invalid target"
    exit 1
    ;;
esac

if [[ -n "$target_option" ]]; then
  $command "$profile" "$target_option"
else
  $command "$profile"
fi
