[color]

;; main colors
background = #101010
foreground = #e6e6e6
foreground-alt = #353535

;; shades
shade1 = #b67262
shade2 = #8a9273
shade3 = #c0a474
shade4 = #78859e
shade5 = #9b859d
shade6 = #a8d2db
shade7 = #e6e6e6
shade8 = #353535

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
