[color]

;; main colors
background = #101010
foreground = #f6f6f6
foreground-alt = #151515

;; shades
shade1 = #b67262
shade2 = #8a9273
shade3 = #c0a474
shade4 = #78859e
shade5 = #9b859d
shade6 = #a8d2db
shade7 = #f6f6f6
shade8 = #151515

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
