[module/lang]
type = custom/script
exec = ~/scripts/polybar/bar/scripts/get-lang
format = %{T1}<label>%{T-}
format-foreground = ${color.shade5}
format-prefix = "%{T2} %{T-}"
format-prefix-foreground = ${color.shade5}
interval = 1.0
click-left = ~/scripts/hardware/chkm &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/ip-tail]
type = custom/script
exec = ~/scripts/polybar/bar/scripts/get-ip
format = %{T1}<label>%{T-}
format-foreground = ${color.shade1}
format-prefix = "%{T2} %{T-}"
format-prefix-foreground = ${color.shade1}
interval = 5

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1.0
time = "%{T2} %{T-}%I:%M"
time-alt = "%{T2}%{T-} %a, %d %b %Y"
format = <label>
format-background = ${color.background}
format-foreground = ${color.shade6}
format-padding = 0
label = "%{T-}%time%"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/i3]
type = internal/i3
pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = true
reverse-scroll = false
fuzzy-match = true
ws-icon-0 = Term;
ws-icon-1 = Media;
ws-icon-2 = Study;
ws-icon-3 = Web;
ws-icon-4 = Game;
ws-icon-5 = Misc;
ws-icon-default = 
format = <label-state><label-mode>
format-padding = 0
format-background = ${color.background}
label-mode = %mode%
label-mode-background = ${color.background}
label-focused = %{T2} %{T-}  %{T1}%name% %{T-}
label-focused-foreground = ${color.foreground}
label-unfocused = %{T1}  %{T-}
label-unfocused-foreground = ${color.foreground}
label-visible = %{T1}  %{T-}
label-urgent = %{T2}  %{T-}
label-urgent-foreground = ${color.shade3}
label-focused-padding = 0
label-urgent-padding = 0
label-unfocused-padding = 0
label-visible-padding = 0
label-mode-padding = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false
interval = 5
format-volume = %{T2}<ramp-volume> %{T1}<label-volume>
format-volume-background = ${color.background}
format-volume-foreground = ${color.shade5}
format-volume-padding = 0
format-muted = %{T1}<label-muted>
format-muted-prefix = %{T2}婢
format-muted-foreground = ${color.shade5}
format-muted-background = ${color.background}
format-muted-padding = 0
label-volume = %percentage%%
label-muted = ""
label-muted-foreground = ${color.shade5}
ramp-volume-0 = 奄
ramp-volume-1 = 奔
ramp-volume-2 = 墳
click-right = bash ~/scripts/rofi/rofi-select-sink &
click-middle = pavucontrol

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout> <label-indicator>
format-prefix = 
format-background = ${color.shade4}
format-padding = 2
label-layout = " %layout%"
label-indicator-on = %name%
label-indicator-on-foreground = ${color.foreground}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/title]
type = internal/xwindow
format = <label>
format-prefix =
format-background = ${color.background}
format-padding = 0
label = "%title%"
label-maxlen = 15
label-empty = ""

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/notifications]
type = custom/script
exec = echo $(dbus-send --session --print-reply=literal --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.ShowNotificationCount 2>/dev/null) | awk '{print $2}'
format = %{T2} %{T1}<label>%{T-}
click-left = exec dbus-send --session --print-reply --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.ShowNotifications 2>/dev/null &
format-foreground = ${color.shade3}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/picom]
type =custom/ipc
hook-0 = echo "%{A1:killall -q picom && polybar-msg hook picom 2:}%{T2}%{T-}%{A}" &
hook-1 = echo "%{A1:picom -b && polybar-msg hook picom 1:}%{T2}%{T-}%{A}" &
initial = 1
format-foreground = ${color.shade3}

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/redshift]
type = custom/script
exec = ~/scripts/polybar/bar/scripts/info-redshift-temp
format = %{T1}<label>%{T-}
format-foreground = ${color.shade4}
format-prefix = "%{T1} %{T-}"
format-prefix-foreground = ${color.shade4}
interval = 5

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/player]
type = custom/script
exec = python3 ~/scripts/polybar/bar/scripts/spotify_status.py -f '{song}' -q -t 45
tail = true
interval = 1
format = <label>
format-foreground = ${color.shade1}
format-prefix = %{T2} %{T-}
format-prefix-foreground = ${color.shade1}
format-padding = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/updates]
type = custom/script

exec = ~/scripts/polybar/bar/scripts/updates.sh
tail = true
interval = 5
format = <label>
format-foreground = ${color.shade2}
format-prefix = %{T2} %{T-}
format-prefix-foreground = ${color.shade2}
format-background = ${color.background}
format-padding = 0
label = %output%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sysmenu]
type = custom/text
content = %{T2}⏻%{T-}

content-background = ${color.background}
content-foreground = ${color.foreground}
content-padding = 1

click-left = ~/scripts/polybar/bar/scripts/powermenu.sh &

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/menu]
type = custom/menu
expand-right = true

menu-0-0 =%{T2} 
menu-0-0-exec = ~/scripts/rofi/launcher &
menu-0-1 =%{T2} 
menu-0-1-exec = pcmanfm &
menu-0-2 = 
menu-0-2-exec = kitty &
menu-0-3 =%{T-}
menu-0-3-exec = brave & 

format = <label-toggle> <menu>
format-background = ${color.shade1}
format-foreground = ${color.background}
format-padding = 2

label-open = "%{T2}%{T-}"
label-close = %{T2}
label-separator = " %{T1}|%{T2} "

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
