[default]
icons = Colloid-grey-light
font0 = JetBrainsMono Nerd Font
font-size = 13
font-size-icon = 14
border-radius = 2
show-icons = true
cursor = phinger-cursors
theme = Orchis-Grey-Light
font1 = SF Mono

[dark]
icons = Colloid-grey
font0 = JetBrainsMono Nerd Font
font-size = 16
font-size-icon = 14
border-radius = 2
show-icons = true
cursor = phinger-cursors
theme = Colloid-Grey-Dark

