[default]
icons = CDE-Reborn
font0 = scientifica
font-size = 13
font-size-icon = 15
border-radius = 2
show-icons = true
cursor = phinger-cursors
theme = cdetheme-solaris
font1 = Source Serif Pro
font-size-alt = 13

[dark]
icons = Colloid-grey
font0 = JetBrainsMono Nerd Font
font-size = 16
font-size-icon = 14
border-radius = 2
show-icons = true
cursor = phinger-cursors
theme = Colloid-Grey-Dark

