[settings]
set_wallpaper = true
gtk = false
active = 1
light_theme = false
editor = kitty -e nvim
execute_cmd = true
command = xsettingsd -c /home/lain/.config/xsettingsd/xsettingsd.conf &
backend = wal
alpha = 100
smart_sort = true
auto_adjust = false
reload = true
vte = true
keywords = default

