[settings]
set_wallpaper = false
gtk = true
active = 1
light_theme = true
editor = kitty -e nvim
execute_cmd = false
command = 
backend = wal
alpha = 100
smart_sort = true
auto_adjust = false
reload = true
vte = true
keywords = default

