# Files and directories #######################################################
music_directory		"/media/music"
playlist_directory		"~/.local/share/mpd/playlists"
db_file			"~/.local/share/mpd/database"
log_file			"~/.local/share/mpd/log"
###############################################################################

# General music daemon options ################################################
bind_to_address		"any"
port				"6600"
restore_paused "no"
auto_update	"yes"
###############################################################################

# Input #######################################################################
input {
        plugin "curl"
}
###############################################################################

# Audio Output ################################################################
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
}
###############################################################################

# Normalization automatic volume adjustments ##################################
replaygain			"off"
###############################################################################

# Character Encoding ##########################################################
filesystem_charset		"UTF-8"
###############################################################################
