; :.config/redshift/redshift.conf
[redshift]
temp-day=6000
temp-night=4000
fade=1
dawn-time=6:00-7:45
dusk-time=18:35-20:15
gamma=1
location-provider=manual
adjustment-method=randr
[randr]
screen=0
[manual]
lat=51.4351
lon=-2.5419
