# :vim: set ft=yaml.ansible:
---
- name: Install and configure base system
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Install collections
      community.general.ansible_galaxy_install:
        type: both
        requirements_file: "requirements.yml"

  roles:
    - aur
    - packages
    - font_maple_mono
    - font_sf_pro
    - font_apple_emoji
    - scripts
