[colors.primary]
background = "#F2F0ED"
bright_foreground = "#4B4039"
dim_foreground = "#D7D1C5"
foreground = "#352F2F"

[colors.normal]
black   = "#F2F0ED"
red     = "#562622"
green   = "#454B39"
yellow =  "#543227"
blue    = "#535367"
magenta = "#735057"
cyan    = "#563E1A"
white   = "#352F2F"

[colors.bright]
black   = "#D7D1C5"
red     = "#562622"
green   = "#454B39"
yellow =  "#543227"
blue    = "#535367"
magenta = "#735057"
cyan    = "#563E1A"
white   = "#4B4039"

[colors.cursor]
cursor = "#79241F"
text = "#F2F0ED"

[colors.footer_bar]
background = "#D7D1C5"
foreground = "#4B4039"

[colors.hints.end]
background = "#79241F"
foreground = "#F2F0ED"

[colors.hints.start]
background = "#562622"
foreground = "#F2F0ED"

[colors.line_indicator]
background = "None"
foreground = "None"
