[colors.primary]
background = "#1D1B19"
bright_foreground = "#282523"
dim_foreground = "#D1B39A"
foreground = "#E3D1C3"

[colors.normal]
black   = "#1D1B19"
red     = "#B0877D"
green   = "#9E9F8C"
yellow =  "#A38E6B"
blue    = "#A1A6B1"
magenta = "#B6A0A9"
cyan    = "#C39474"
white   = "#E3D1C3"

[colors.bright]
black   = "#282523"
red     = "#B0877D"
green   = "#9E9F8C"
yellow =  "#A38E6B"
blue    = "#A1A6B1"
magenta = "#B6A0A9"
cyan    = "#C39474"
white   = "#D1B39A"

[colors.cursor]
cursor = "#F0644A"
text = "#E3D1C3"

[colors.footer_bar]
background = "#282523"
foreground = "#D1B39A"

[colors.hints.end]
background = "#F0644A"
foreground = "#1D1B19"

[colors.hints.start]
background = "#AC7A73"
foreground = "#1D1B19"

[colors.line_indicator]
background = "None"
foreground = "None"
