#!/bin/bash

oext='md'
for infile in $@; do
    [ -e "$infile" ] || continue
    ext="${infile##*.}"
    base=$(basename "$infile" "$ext")
    dir=$(dirname "$infile")
    outfile="$dir"/"$base""$oext"
    if [ ! -f "$outfile" ]
    then
        sed -f - "$infile" > "$outfile" <<- '            SED_SCRIPT'
            s/# \(.*\)$/* \1/g
            s/^= \(.*\) =$/# \1/g
            s/^== \(.*\) ==$/## \1/g
            s/^=== \(.*\) ===$/### \1/g
            s/^==== \(.*\) ====$/#### \1/g
            s/^===== \(.*\) =====$/##### \1/g
            s/^====== \(.*\) ======$/###### \1/g
            s/{{{class="brush: *\([^"]*\)"/\`\`\`\1/g
            s/{{{class="\([^"]*\)"/\`\`\`\1/g
            s/{{{/\`\`\`/g
            s/}}}/\`\`\`/g
            s/\[\[\(\([^|]\{1,\}\)\|\)\([^]]\{1,\}\)\]\]/[\3](\2)/g;s/.|/[/
            s/\[\[\([^]]\{1,\}\)\]\]/[\1](\1.md)/g
            s/%% \(.*\)/<!-- \1 -->/g
            /%toc.*/d
            s/%title \(.*\)/# \1/g
            s/%nohtml/- status: draft/g
            SED_SCRIPT
        echo "CONVERTED:  $outfile"
    else
        echo "skipped:    $outfile"
    fi
done
#s/\[\[\(\(https\:\/\/[^|]\{1,\}\)\|\)\([^]]\{1,\}\)\]\]/[\3](\2.md)/g;s/.|/[/
