;; vim:set ft=dosini:
;;+-----------------------------------------+
;;|               _       _                 |
;;|   _ __   ___ | |_   _| |__   __ _ _ __  |
;;|  | '_ \ / _ \| | | | | '_ \ / _` | '__| |
;;|  | |_) | (_) | | |_| | |_) | (_| | |    |
;;|  | .__/ \___/|_|\__, |_.__/ \__,_|_|    |
;;|  |_|            |___/                   |
;;|                                         |
;;+-----------------------------------------+
[global/wm]
margin-bottom = 0
margin-top = 0
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; File Inclusion
include-file = ~/.config/polybar/bar/modules.ini
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; Bar Settings
[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
wm-restack = i3
bottom = false
fixed-center = true
width = 100%
height = 56
offset-x = 0%
offset-y = 0%
background = #202020
foreground = #a19d94
radius-top = 0.0
radius-bottom = 0.0
underline-size = 2
underline-color = #a19d94
border-size = 0
border-color = #202020
padding-left = 1
padding-right = 2
module-margin-left = 1
module-margin-right = 1
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; Fonts
font-0 = "JetBrainsMono:pixelsize=17;3"
font-1 = "JetBrainsMono Nerd Font:pixelsize=14;3"
font-2 = "Noto Sans:pixelsize=12;3"
font-3 = "WenQuanYi Zen Hei Mono:pixelsize=12;3"
font-4 = "JetBrainsMono:style=Bold:pixelsize=17;3"
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; Modules
modules-left = date player
modules-center = i3
modules-right = lang notifications picom taskwarrior updates pulseaudio
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; General
separator =
dim-value = 1.0
wm-name = i3
locale = en_GB.UTF-8
tray-position = off
tray-detached = false
tray-maxsize = 16
tray-background = #202020
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
enable-ipc = true
click-left =
click-middle =
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click =
cursor-scroll =
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; Application Settings
[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
